package ex_27_Exceptions;

public class Lab105_try_catch_multipleIQ
    {
        public static void main(String[] args)
        {
            System.out.println("1");
            try
            {
                int a = 10 / 2;
            }
            catch (Exception e)
            {
                System.out.println("Are you fool, Divide by zero");
            }

        }

        }

